sudo: false
language: node_js
node_js:
  - "5.5"
branches:
  only:
    - gh-pages
    - /.*/
before_install: npm install -g fast-xml-parser
script: 
  - [ -f *.html ] && xml2js -V *.html 
  - [ -f *.htm ] && xml2js -V *.htm 
  - [ -f *.xml ] && xml2js -V *.xml 
  - [ -f *.x3d ] && xml2js -V *.x3d
cache:
  directories:
    - node_modules
notifications:
  email: false
