sudo: false
language: node_js
node_js:
  - "5.5"
branches:
  only:
    - gh-pages
    - /.*/
before_install: npm install -g fast-xml-parser
script: 
  xml2js -V *.html && xml2js -V *.htm && xml2js -V *.xml && xml2js -V *.x3d
cache:
  directories:
    - node_modules
notifications:
  email: false
